/**
 * Sends a Purchase Order email using the Brevo API (v3) via Native Fetch.
 */
const sendPurchaseOrderEmail = async (supplier, purchaseOrder) => {
    // 1. Validation
    if (!supplier?.email) {
        return { success: false, message: 'Supplier has no email address' };
    }

    const apiKey = (process.env.BREVO_API_KEY || '').trim();
    const senderEmail = (process.env.BREVO_SENDER_EMAIL).trim();

    if (!apiKey) {
        return { success: false, message: 'API Key missing' };
    }

    // 2. Build Item Table Rows
    const items = purchaseOrder.purchase_order_items || [];
    const itemsHtml = items.map(item => `
        <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0;">${item.item?.name || 'N/A'}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-family: monospace; font-size: 12px;">${item.item?.code || 'N/A'}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: center;">${item.quantity}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: right;">Rs ${Number(item.expected_price || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: right; font-weight: bold;">Rs ${(Number(item.quantity || 0) * Number(item.expected_price || 0)).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
        </tr>
    `).join('');

    // 3. Build HTML Content
    const htmlContent = `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 650px; margin: auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; color: #1e293b;">
            <div style="background-color: #2563eb; padding: 24px; color: white; text-align: center;">
                <h1 style="margin: 0; font-size: 24px;">Purchase Order</h1>
                <p style="margin: 4px 0 0; opacity: 0.9;">Order Reference: #${purchaseOrder.id}</p>
            </div>
            
            <div style="padding: 30px;">
                <p style="font-size: 16px;">Dear <strong>${supplier.name}</strong>,</p>
                <p>Please find the details of our new purchase order below. We look forward to receiving these items at your earliest convenience.</p>
                
                <table style="width: 100%; border-collapse: collapse; margin: 24px 0; font-size: 14px;">
                    <thead>
                        <tr style="background-color: #f8fafc; color: #64748b; text-transform: uppercase; font-size: 11px; letter-spacing: 0.05em;">
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: left;">Item</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: left;">SKU/Code</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: center;">Qty</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: right;">Unit Price</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: right;">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${itemsHtml}
                    </tbody>
                    <tfoot>
                        <tr style="background-color: #f8fafc;">
                            <td colspan="4" style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: right; font-weight: 600;">Grand Total</td>
                            <td style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: right; font-weight: 800; color: #2563eb; font-size: 16px;">
                                Rs ${Number(purchaseOrder.total_amount || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                            </td>
                        </tr>
                    </tfoot>
                </table>

                <div style="background-color: #f1f5f9; padding: 16px; border-radius: 6px; font-size: 13px;">
                    <p style="margin: 0;"><strong>Order Date:</strong> ${new Date(purchaseOrder.order_date).toLocaleDateString()}</p>
                </div>
                
                <div style="margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #94a3b8; text-align: center;">
                    <p>This is an automated purchase order generated by the Inventory Management System.</p>
                    <p>&copy; ${new Date().getFullYear()} IMS Inventory System</p>
                </div>
            </div>
        </div>
    `;

    // 4. Send via Brevo API
    try {
        const response = await fetch('https://api.brevo.com/v3/smtp/email', {
            method: 'POST',
            headers: {
                'api-key': apiKey,
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            },
            body: JSON.stringify({
                subject: `New Purchase Order - #${purchaseOrder.id}`,
                sender: { name: "IMS Inventory", email: senderEmail },
                to: [{ email: supplier.email, name: supplier.name }],
                htmlContent: htmlContent
            })
        });

        const result = await response.json();

        if (response.ok) {
            return { success: true, messageId: result.messageId };
        } else {
            return { success: false, error: result.message };
        }
    } catch (error) {
        return { success: false, error: error.message };
    }
};

const sendGrnEmail = async (supplier, grn, items, totals, userName, userRole) => {
    // 1. Validation
    if (!supplier?.email) {
        return { success: false, message: 'Supplier has no email address' };
    }

    const apiKey = (process.env.BREVO_API_KEY || '').trim();
    const senderEmail = (process.env.BREVO_SENDER_EMAIL || '').trim();

    if (!apiKey) {
        return { success: false, message: 'API Key missing' };
    }

    // 2. Build Item Table Rows
    const itemsHtml = items.map(item => `
        <tr>
            <td style="padding: 10px; border: 1px solid #e2e8f0;">${item.name || 'N/A'}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; font-family: monospace; font-size: 12px;">${item.sku || 'N/A'}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: center;">${item.totalQty}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: center; color: #059669; font-weight: bold;">${item.receivedQty}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: center; color: ${item.balanceQty > 0 ? '#b45309' : '#059669'};">${item.balanceQty}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: right;">Rs ${Number(item.unitPrice || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
            <td style="padding: 10px; border: 1px solid #e2e8f0; text-align: right; font-weight: bold;">Rs ${Number(item.subtotal || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
        </tr>
    `).join('');

    // 3. Build HTML Content
    const htmlContent = `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 700px; margin: auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; color: #1e293b;">
            <div style="background-color: #004ac6; padding: 24px; color: white; text-align: center;">
                <h1 style="margin: 0; font-size: 24px;">Goods Received Note</h1>
                <p style="margin: 4px 0 0; opacity: 0.9;">GRN Reference: ${grn.grn_no || `GRN-${grn.id}`}</p>
            </div>
            
            <div style="padding: 30px;">
                <p style="font-size: 16px;">Dear <strong>${supplier.name}</strong>,</p>
                <p>We are pleased to acknowledge the receipt of the following items against <strong>PO: ${grn.poNumber || grn.purchase_order?.po_no || 'N/A'}</strong>.</p>
                
                <table style="width: 100%; border-collapse: collapse; margin: 24px 0; font-size: 13px;">
                    <thead>
                        <tr style="background-color: #f8fafc; color: #64748b; text-transform: uppercase; font-size: 10px; letter-spacing: 0.05em;">
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: left;">Item</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: left;">SKU</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: center;">Total</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: center;">Rcvd</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: center;">Bal</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: right;">Price</th>
                            <th style="padding: 12px 10px; border: 1px solid #e2e8f0; text-align: right;">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${itemsHtml}
                    </tbody>
                </table>

                <div style="display: flex; justify-content: flex-end; margin-bottom: 24px;">
                    <table style="width: 250px; border-collapse: collapse; font-size: 14px;">
                        <tr>
                            <td style="padding: 8px 0; color: #64748b;">Subtotal</td>
                            <td style="padding: 8px 0; text-align: right; font-weight: 600;">Rs ${Number(totals.subtotal || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 0; color: #64748b;">Balance Value</td>
                            <td style="padding: 8px 0; text-align: right; font-weight: 600; color: ${totals.balanceValue > 0 ? '#b45309' : '#059669'};">Rs ${Number(totals.balanceValue || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                        </tr>
                        <tr style="border-top: 1px solid #e2e8f0;">
                            <td style="padding: 12px 0; font-weight: 700; font-size: 16px;">Grand Total</td>
                            <td style="padding: 12px 0; text-align: right; font-weight: 800; color: #004ac6; font-size: 18px;">Rs ${Number(totals.grandTotal || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                        </tr>
                    </table>
                </div>

                <div style="background-color: #f1f5f9; padding: 16px; border-radius: 6px; font-size: 13px; display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
                    <div><strong>Received Date:</strong> ${new Date(grn.grn_date || grn.createdAt).toLocaleDateString()}</div>
                    <div><strong>Status:</strong> ${grn.status || grn.grn_status?.name || 'Processed'}</div>
                    <div><strong>Processed By:</strong> ${userName} (${userRole})</div>
                </div>
                
                <div style="margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #94a3b8; text-align: center;">
                    <p>This is a computer-generated Goods Received Note.</p>
                    <p>&copy; ${new Date().getFullYear()} IMS Inventory System</p>
                </div>
            </div>
        </div>
    `;

    // 4. Send via Brevo API
    try {
        const response = await fetch('https://api.brevo.com/v3/smtp/email', {
            method: 'POST',
            headers: {
                'api-key': apiKey,
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            },
            body: JSON.stringify({
                subject: `Goods Received Note - ${grn.grn_no || `GRN-${grn.id}`}`,
                sender: { name: "IMS Inventory", email: senderEmail },
                to: [{ email: supplier.email, name: supplier.name }],
                htmlContent: htmlContent
            })
        });

        const result = await response.json();

        if (response.ok) {
            return { success: true, messageId: result.messageId };
        } else {
            return { success: false, error: result.message };
        }
    } catch (error) {
        return { success: false, error: error.message };
    }
};

module.exports = {
    sendPurchaseOrderEmail,
    sendGrnEmail,
};

